#!/usr/bin/env bash
#
# Run the Polaris Iceberg ingestion once, against the OpenMetadata server.
#
# The workflow needs the ingestion-bot's JWT. That token is generated by the
# server at start-up rather than fixed in configuration, so it is fetched here:
# log in as the default admin, look the bot up, read its auth mechanism. Set
# OM_JWT_TOKEN to skip all of that (for example with a token copied from
# Settings -> Bots in the UI).
#
set -euo pipefail

OM_HOST="${OM_HOST:-http://openmetadata-server:8585}"
OM_ADMIN_EMAIL="${OM_ADMIN_EMAIL:-admin@open-metadata.org}"
OM_ADMIN_PASSWORD="${OM_ADMIN_PASSWORD:-admin}"
WORKFLOW="${WORKFLOW:-/workflow/polaris-ingestion.yaml}"

log() { printf '  %s\n' "$*"; }

echo "==> waiting for OpenMetadata at ${OM_HOST}"
for attempt in $(seq 1 120); do
  if curl -sf "${OM_HOST}/api/v1/system/version" >/dev/null 2>&1; then
    log "up after ${attempt}s"
    break
  fi
  if [ "${attempt}" = "120" ]; then
    echo "FATAL: OpenMetadata did not answer within 120s" >&2
    exit 1
  fi
  sleep 1
done

if [ -z "${OM_JWT_TOKEN:-}" ]; then
  echo "==> fetching the ingestion-bot token"

  # The basic auth provider expects the password base64-encoded.
  encoded_password="$(printf '%s' "${OM_ADMIN_PASSWORD}" | base64 | tr -d '\n')"
  login_response="$(curl -sS -X POST "${OM_HOST}/api/v1/users/login" \
    -H 'Content-Type: application/json' \
    -d "{\"email\":\"${OM_ADMIN_EMAIL}\",\"password\":\"${encoded_password}\"}")"

  admin_token="$(printf '%s' "${login_response}" | jq -r '.accessToken // empty')"
  if [ -z "${admin_token}" ]; then
    echo "FATAL: could not log in as ${OM_ADMIN_EMAIL}." >&2
    echo "       Response: ${login_response}" >&2
    echo "       Set OM_JWT_TOKEN to the ingestion-bot token to bypass this." >&2
    exit 1
  fi

  bot_user_id="$(curl -sS "${OM_HOST}/api/v1/bots/name/ingestion-bot" \
    -H "Authorization: Bearer ${admin_token}" | jq -r '.botUser.id // empty')"
  if [ -z "${bot_user_id}" ]; then
    echo "FATAL: the ingestion-bot has no bot user" >&2
    exit 1
  fi

  OM_JWT_TOKEN="$(curl -sS \
    "${OM_HOST}/api/v1/users/${bot_user_id}?fields=authenticationMechanism" \
    -H "Authorization: Bearer ${admin_token}" \
    | jq -r '.authenticationMechanism.config.JWTToken // empty')"

  if [ -z "${OM_JWT_TOKEN}" ]; then
    echo "FATAL: could not read the ingestion-bot's JWT" >&2
    exit 1
  fi
  log "got a token (${#OM_JWT_TOKEN} chars)"
fi

# Rendered to a new file so the token never lands in the mounted source.
rendered="$(mktemp /tmp/polaris-ingestion.XXXXXX.yaml)"
trap 'rm -f "${rendered}"' EXIT
sed "s|__JWT_TOKEN__|${OM_JWT_TOKEN}|" "${WORKFLOW}" > "${rendered}"

echo "==> ingesting"
metadata ingest -c "${rendered}"

cat <<'SUMMARY'

==> ingestion complete

    Open http://localhost:8585 and look under
      Settings -> Services -> Databases -> polaris

    Expected:
      database   poc_catalog
      schemas    shared, restricted
      tables     shared.events, restricted.salaries  (columns and types)

    The crawler reached Polaris as the Keycloak client `openmetadata`
    (OAuth 2.0 client credentials), which the AuthZEN PDP allows to read
    metadata everywhere and to write nothing.
SUMMARY
